FROM public.ecr.aws/amazonlinux/amazonlinux:2 as installer
ENV AWS_CLI_VER=2.7.34
ARG EXE_FILENAME=awscli-exe-linux-x86_64-${AWS_CLI_VER}.zip
RUN yum update -y \
  && yum install -y unzip \
  && curl -s https://awscli.amazonaws.com/${EXE_FILENAME} -o ${EXE_FILENAME} \
  && unzip ${EXE_FILENAME} \
  # The --bin-dir is specified so that we can copy the
  # entire bin directory from the installer stage into
  # into /usr/local/bin of the final stage without
  # accidentally copying over any other executables that
  # may be present in /usr/local/bin of the installer stage.
  && ./aws/install --bin-dir /aws-cli-bin/

FROM public.ecr.aws/amazonlinux/amazonlinux:2
RUN yum update -y \
  && yum install -y less groff \
  && yum clean all
COPY --from=installer /usr/local/aws-cli/ /usr/local/aws-cli/
COPY --from=installer /aws-cli-bin/ /usr/local/bin/
WORKDIR /aws
ENTRYPOINT ["/usr/local/bin/aws"]
